version: '3'
services:
  web:
    container_name: web
    build:
        context: .
    ports: 
      - 3000:3000
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:5.0.25
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes: 
  data:

